! subversion Id for THIS file : $Id: spc_names.f 8506 2016-01-28 10:09:58Z simonc $
! $URL: http://svn-ae/ae/COMMON/stand-alone/atmos_models/socrates/tags/07.18.01/src/preproc/src/spc_names.f $
!-----------------------------------------------------------------------

      subroutine MAKE_NAME_MOD( spc_cnt, spc_names )
!--------------------------------------------------------------------------------
!	... Makes a module of parameter species names
!--------------------------------------------------------------------------------

      implicit none

!--------------------------------------------------------------------------------
!	... Dummy args
!--------------------------------------------------------------------------------
      integer, intent(in) :: spc_cnt
      character(len=8), intent(in) :: spc_names(64)

!--------------------------------------------------------------------------------
!	... Local variables
!--------------------------------------------------------------------------------
      integer :: i
      character(len=80) :: buff, line
      logical :: lexist

!--------------------------------------------------------------------------------
!	... Check mod file existence; remove if found
!--------------------------------------------------------------------------------
      INQUIRE( file = 'spc_names.mod', exist = lexist )
      if( lexist ) then
         call SYSTEM( 'rm spc_names.mod' )
      end if
      OPEN( unit = 30, &
	    file = 'spc_names.mod' )
             
      line = '! DO NOT EDIT THIS FILE!! It was automatically written by'
      write(30,'(a)') TRIM( line )
      line = '! the socpp program. Use that program and its *.in input file'
      write(30,'(a)') TRIM( line )
      line = '! (see directory preproc/ ) to overwrite it'
      write(30,'(a)') TRIM( line )
      line = '!============================================================'
      write(30,'(a)') TRIM( line )
      buff = ''
      write(30,'(a)') buff
      buff(7:) = 'module SPC_NAMES'
      write(30,'(a)') buff
      buff = ''
      write(30,'(a)') buff
      do i = 1,spc_cnt
	 write(buff(7:),'(''integer, parameter :: vid_'',a,1x,''='',1x,i3)') &
	             spc_names(i)(:LEN_TRIM(spc_names(i))), i
         write(30,'(a)') buff
      end do
      buff = ''
      write(30,'(a)') buff
      buff(7:) = 'end module SPC_NAMES'
      write(30,'(a)') buff
      CLOSE(30)

      end subroutine MAKE_NAME_MOD
