! subversion Id for THIS file : $Id: preprocessed.mod.f 8506 2016-01-28 10:09:58Z simonc $
! $URL: http://svn-ae/ae/COMMON/stand-alone/atmos_models/socrates/tags/07.18.01/src/preprocessed.mod.f $
!-----------------------------------------------------------------------
! DO NOT EDIT THIS FILE!! It was automatically written by
! the socpp program. Use that program and its *.in input file
! (see directory preproc/ ) to overwrite it
!============================================================

      module SPC_NAMES

      integer, parameter :: vid_n2o =   1
      integer, parameter :: vid_ch4 =   2
      integer, parameter :: vid_h2o =   3
      integer, parameter :: vid_co =   4
      integer, parameter :: vid_hcl =   5
      integer, parameter :: vid_hbr =   6
      integer, parameter :: vid_co2 =   7
      integer, parameter :: vid_h2 =   8
      integer, parameter :: vid_ch2o =   9
      integer, parameter :: vid_cfc10 =  10
      integer, parameter :: vid_cfc11 =  11
      integer, parameter :: vid_cfc12 =  12
      integer, parameter :: vid_cfc113 =  13
      integer, parameter :: vid_cfc114 =  14
      integer, parameter :: vid_cfc115 =  15
      integer, parameter :: vid_hcfc22 =  16
      integer, parameter :: vid_ch3ccl3 =  17
      integer, parameter :: vid_ch3cl =  18
      integer, parameter :: vid_ha1211 =  19
      integer, parameter :: vid_ha1301 =  20
      integer, parameter :: vid_hf =  21
      integer, parameter :: vid_ch3br =  22
      integer, parameter :: vid_chbr3 =  23
      integer, parameter :: vid_o3 =  24
      integer, parameter :: vid_o3p =  25
      integer, parameter :: vid_o1d =  26
      integer, parameter :: vid_h =  27
      integer, parameter :: vid_oh =  28
      integer, parameter :: vid_ho2 =  29
      integer, parameter :: vid_h2o2 =  30
      integer, parameter :: vid_cl =  31
      integer, parameter :: vid_cl2 =  32
      integer, parameter :: vid_clo =  33
      integer, parameter :: vid_oclo =  34
      integer, parameter :: vid_hocl =  35
      integer, parameter :: vid_clono2 =  36
      integer, parameter :: vid_clno2 =  37
      integer, parameter :: vid_cl2o2 =  38
      integer, parameter :: vid_n =  39
      integer, parameter :: vid_no =  40
      integer, parameter :: vid_no2 =  41
      integer, parameter :: vid_no3 =  42
      integer, parameter :: vid_hno3 =  43
      integer, parameter :: vid_n2o5 =  44
      integer, parameter :: vid_ho2no2 =  45
      integer, parameter :: vid_br =  46
      integer, parameter :: vid_bro =  47
      integer, parameter :: vid_hobr =  48
      integer, parameter :: vid_brono2 =  49
      integer, parameter :: vid_brcl =  50
      integer, parameter :: vid_ch3o2 =  51
      integer, parameter :: vid_ch3ooh =  52
      integer, parameter :: vid_o2 =  53
      integer, parameter :: vid_o2dg =  54
      integer, parameter :: vid_o2s =  55
      integer, parameter :: vid_x =  56

      end module SPC_NAMES

      module RXT_NAMES

      integer, parameter :: rid_jo2_op =    1
      integer, parameter :: rid_jo2_od =    2
      integer, parameter :: rid_jo3_op =    3
      integer, parameter :: rid_jh2o =    4
      integer, parameter :: rid_jn2o =    5
      integer, parameter :: rid_jco2 =    6
      integer, parameter :: rid_jch4 =    7
      integer, parameter :: rid_jno2 =    8
      integer, parameter :: rid_jhno3 =    9
      integer, parameter :: rid_jcfc12 =   10
      integer, parameter :: rid_jcfc11 =   11
      integer, parameter :: rid_jcfc10 =   12
      integer, parameter :: rid_jhocl =   13
      integer, parameter :: rid_jch3ccl3 =   14
      integer, parameter :: rid_jhno4_1 =   15
      integer, parameter :: rid_jhno4_2 =   16
      integer, parameter :: rid_jch3cl =   17
      integer, parameter :: rid_jclno4_1 =   18
      integer, parameter :: rid_jn2o5 =   19
      integer, parameter :: rid_jo3_od =   20
      integer, parameter :: rid_jcfc113 =   21
      integer, parameter :: rid_jhcfc22 =   22
      integer, parameter :: rid_jha1211 =   23
      integer, parameter :: rid_jha1301 =   24
      integer, parameter :: rid_jh2o2 =   25
      integer, parameter :: rid_jch2o_h =   26
      integer, parameter :: rid_jch2o_h2 =   27
      integer, parameter :: rid_jbrono2 =   28
      integer, parameter :: rid_jhobr =   29
      integer, parameter :: rid_jch3br =   30
      integer, parameter :: rid_joclo =   31
      integer, parameter :: rid_jcl2o2 =   32
      integer, parameter :: rid_jcl2 =   33
      integer, parameter :: rid_jcfc114 =   34
      integer, parameter :: rid_jcfc115 =   35
      integer, parameter :: rid_jhcl =   36
      integer, parameter :: rid_jclno2 =   37
      integer, parameter :: rid_jno3_no2 =   38
      integer, parameter :: rid_jno =   39
      integer, parameter :: rid_jbrcl =   40
      integer, parameter :: rid_jbro =   41
      integer, parameter :: rid_jclno4_2 =   42
      integer, parameter :: rid_jno3_no =   43
      integer, parameter :: rid_jchbr3 =   44
      integer, parameter :: rid_jch3ooh =   45
      integer, parameter :: rid_jho2 =   46
      integer, parameter :: rid_j_o2s =   47
      integer, parameter :: rid_a1 =   48
      integer, parameter :: rid_a1et =   49
      integer, parameter :: rid_a3et =   50
      integer, parameter :: rid_a2 =   51
      integer, parameter :: rid_a5 =   52
      integer, parameter :: rid_a6 =   53
      integer, parameter :: rid_a6b =   54
      integer, parameter :: rid_a7 =   55
      integer, parameter :: rid_a17 =   56
      integer, parameter :: rid_a19 =   57
      integer, parameter :: rid_a23a =   58
      integer, parameter :: rid_a23b =   59
      integer, parameter :: rid_a23c =   60
      integer, parameter :: rid_a24 =   61
      integer, parameter :: rid_a26 =   62
      integer, parameter :: rid_a27 =   63
      integer, parameter :: rid_a30 =   64
      integer, parameter :: rid_a36 =   65
      integer, parameter :: rid_a81 =   66
      integer, parameter :: rid_a82 =   67
      integer, parameter :: rid_a83 =   68
      integer, parameter :: rid_b3 =   69
      integer, parameter :: rid_b4 =   70
      integer, parameter :: rid_b6 =   71
      integer, parameter :: rid_b7 =   72
      integer, parameter :: rid_b9 =   73
      integer, parameter :: rid_b12 =   74
      integer, parameter :: rid_b22 =   75
      integer, parameter :: rid_b23 =   76
      integer, parameter :: rid_b24 =   77
      integer, parameter :: rid_b27 =   78
      integer, parameter :: rid_b28 =   79
      integer, parameter :: rid_b32 =   80
      integer, parameter :: rid_b38 =   81
      integer, parameter :: rid_b39 =   82
      integer, parameter :: rid_b71 =   83
      integer, parameter :: rid_b72 =   84
      integer, parameter :: rid_b73a =   85
      integer, parameter :: rid_b73b =   86
      integer, parameter :: rid_b81 =   87
      integer, parameter :: rid_b82 =   88
      integer, parameter :: rid_b84 =   89
      integer, parameter :: rid_c1 =   90
      integer, parameter :: rid_c1a =   91
      integer, parameter :: rid_c1b =   92
      integer, parameter :: rid_c2 =   93
      integer, parameter :: rid_c3 =   94
      integer, parameter :: rid_c5 =   95
      integer, parameter :: rid_c7 =   96
      integer, parameter :: rid_c8 =   97
      integer, parameter :: rid_c9 =   98
      integer, parameter :: rid_c10 =   99
      integer, parameter :: rid_c17 =  100
      integer, parameter :: rid_c44 =  101
      integer, parameter :: rid_d0 =  102
      integer, parameter :: rid_d1 =  103
      integer, parameter :: rid_d2 =  104
      integer, parameter :: rid_d3 =  105
      integer, parameter :: rid_d4 =  106
      integer, parameter :: rid_d5 =  107
      integer, parameter :: rid_d6 =  108
      integer, parameter :: rid_d7 =  109
      integer, parameter :: rid_d8 =  110
      integer, parameter :: rid_d8a =  111
      integer, parameter :: rid_d10 =  112
      integer, parameter :: rid_d11 =  113
      integer, parameter :: rid_d31 =  114
      integer, parameter :: rid_d32 =  115
      integer, parameter :: rid_d33 =  116
      integer, parameter :: rid_d33a =  117
      integer, parameter :: rid_d34 =  118
      integer, parameter :: rid_d35 =  119
      integer, parameter :: rid_d36 =  120
      integer, parameter :: rid_d37 =  121
      integer, parameter :: rid_d47 =  122
      integer, parameter :: rid_d48 =  123
      integer, parameter :: rid_d49 =  124
      integer, parameter :: rid_d50 =  125
      integer, parameter :: rid_d52 =  126
      integer, parameter :: rid_d60 =  127
      integer, parameter :: rid_d61 =  128
      integer, parameter :: rid_d62 =  129
      integer, parameter :: rid_d63 =  130
      integer, parameter :: rid_d64 =  131
      integer, parameter :: rid_d65 =  132
      integer, parameter :: rid_d71 =  133
      integer, parameter :: rid_d72 =  134
      integer, parameter :: rid_d73 =  135
      integer, parameter :: rid_d74 =  136
      integer, parameter :: rid_d75 =  137
      integer, parameter :: rid_d81 =  138
      integer, parameter :: rid_d82 =  139
      integer, parameter :: rid_d83 =  140
      integer, parameter :: rid_d84 =  141
      integer, parameter :: rid_d85 =  142
      integer, parameter :: rid_d87 =  143
      integer, parameter :: rid_d101 =  144
      integer, parameter :: rid_d102 =  145
      integer, parameter :: rid_d103 =  146
      integer, parameter :: rid_d104 =  147
      integer, parameter :: rid_d105 =  148
      integer, parameter :: rid_d106 =  149
      integer, parameter :: rid_d107 =  150
      integer, parameter :: rid_e0 =  151
      integer, parameter :: rid_e1 =  152
      integer, parameter :: rid_e2 =  153
      integer, parameter :: rid_e3 =  154
      integer, parameter :: rid_e4 =  155
      integer, parameter :: rid_e5a =  156
      integer, parameter :: rid_e5b =  157
      integer, parameter :: rid_e5c =  158
      integer, parameter :: rid_e6 =  159
      integer, parameter :: rid_e7 =  160
      integer, parameter :: rid_e8 =  161
      integer, parameter :: rid_e9 =  162
      integer, parameter :: rid_e11 =  163
      integer, parameter :: rid_e13 =  164
      integer, parameter :: rid_e15 =  165
      integer, parameter :: rid_e71 =  166
      integer, parameter :: rid_e72 =  167
      integer, parameter :: rid_e81 =  168
      integer, parameter :: rid_e91 =  169
      integer, parameter :: rid_e92 =  170
      integer, parameter :: rid_e93 =  171
      integer, parameter :: rid_hk1 =  172
      integer, parameter :: rid_hk2 =  173
      integer, parameter :: rid_hk3 =  174
      integer, parameter :: rid_hk4 =  175
      integer, parameter :: rid_hk5a =  176
      integer, parameter :: rid_hk5b =  177
      integer, parameter :: rid_hk7a =  178
      integer, parameter :: rid_hk7b =  179
      integer, parameter :: rid_hk8 =  180
      integer, parameter :: rid_hk9 =  181
      integer, parameter :: rid_hk10 =  182
      integer, parameter :: rid_hk12 =  183
      integer, parameter :: rid_hk13 =  184
      integer, parameter :: rid_hk14 =  185
      integer, parameter :: rid_hk15 =  186
      integer, parameter :: rid_hk16 =  187
      integer, parameter :: rid_hk21 =  188
      integer, parameter :: rid_hk30 =  189
      integer, parameter :: rid_hk31 =  190
      integer, parameter :: rid_g1 =  191
      integer, parameter :: rid_g2 =  192
      integer, parameter :: rid_het1 =  193
      integer, parameter :: rid_het2 =  194
      integer, parameter :: rid_het3 =  195
      integer, parameter :: rid_het4 =  196
      integer, parameter :: rid_het5 =  197
      integer, parameter :: rid_PMChet1 =  198
      integer, parameter :: rid_PMChet2 =  199
      integer, parameter :: rid_PMChet3 =  200
      integer, parameter :: rid_PMChet4 =  201
      integer, parameter :: rid_PMChet5 =  202

      end module RXT_NAMES

      module SPECIES_DIMS

      implicit none

      integer, parameter :: nbcon = 56  ! number of variable species
      integer, parameter :: nfs = 2      ! number of "fixed" species

      end module SPECIES_DIMS

      module CHEM_MODS
!--------------------------------------------------------------
!     	... Basic chemistry array parameters
!------------------------------------------------------------------

      implicit none

      integer, parameter :: hetcnt = 7,   ! number of heterogeneous processes
     $                      phtcnt = 47,   ! number of photo processes
     $                      rxncnt = 202,   ! number of total reactions
     $                      nextcnt = 1

      integer   :: clscnt(5)
      integer   :: cls_rxt_cnt(4,5)
      integer, dimension(56,5) ::
     $             clsmap
     $,            base2cls
     $,            permute
     $,            permute_orig

      integer   :: diag_map(56)

      end module CHEM_MODS

      module TRACNM
!-----------------------------------------------------------
! 	... List of advected and non-advected trace species, and
!           surface fluxes for the advected species.
!-----------------------------------------------------------
      character(len=8) :: solsym(56)   ! species names

      end module TRACNM

