! subversion Id for THIS file : $Id: socpp-setrxt.f 8506 2016-01-28 10:09:58Z simonc $
! $URL: http://svn-ae/ae/COMMON/stand-alone/atmos_models/socrates/tags/07.18.01/src/socpp-setrxt.f $
!-----------------------------------------------------------------------
! DO NOT EDIT THIS FILE!! It was automatically written by
! the socpp program. Use that program and its *.in input file
! (see directory preproc/ ) to overwrite it
!============================================================

      subroutine SETRXT( lat,
     $                   temp )
!----------------------------------------------
!       ... Set chemical reaction rates
!----------------------------------------------

      use RXT_NAMES
      use RATES_MODS, rate => rxt_rates

      implicit none

!----------------------------------------------
!       ... Dummy args
!----------------------------------------------
      integer, intent(in)  ::     lat
      real, intent(in)  ::     temp(121)

!----------------------------------------------
!       ... Local variables
!----------------------------------------------
      real    :: itemp(121)

!----------------------------------------------
!       ... Cst reaction rates - some waste of CPU here
!----------------------------------------------
      rate(:,rid_a1et,:) = 2.2e-10
      rate(:,rid_a3et,:) = 1.1e-10
      rate(:,rid_a23a,:) = 7.29e-11
      rate(:,rid_a23b,:) = 6.48e-12
      rate(:,rid_a23c,:) = 1.622e-12
      rate(:,rid_b38,:) = 4.9e-11
      rate(:,rid_b39,:) = 6.7e-11
      rate(:,rid_b71,:) = 1.e-11
      rate(:,rid_b72,:) = 2.2e-11
      rate(:,rid_b73a,:) = 2.8e-12
      rate(:,rid_b73b,:) = 7e-13
      rate(:,rid_c1,:) = 1.5e-10
      rate(:,rid_c1a,:) = 1.5e-11
      rate(:,rid_c8,:) = 1e-11
      rate(:,rid_d35,:) = 1.7e-13
      rate(:,rid_d71,:) = 2.8e-10
      rate(:,rid_d72,:) = 1e-10
      rate(:,rid_d73,:) = 2.4e-11
      rate(:,rid_d74,:) = 4.7e-13
      rate(:,rid_d75,:) = 1.5e-10
      rate(:,rid_d101,:) = 3.3e-10
      rate(:,rid_d102,:) = 2.3e-10
      rate(:,rid_d103,:) = 1.4e-10
      rate(:,rid_d104,:) = 2e-10
      rate(:,rid_d105,:) = 1.3e-10
      rate(:,rid_d106,:) = 5e-11
      rate(:,rid_d107,:) = 1e-10
      rate(:,rid_e11,:) = 1.1e-11
      rate(:,rid_e71,:) = 1.5e-10
      rate(:,rid_e72,:) = 7.5e-11
      rate(:,rid_e91,:) = 1e-10
      rate(:,rid_e92,:) = 1.5e-10
      rate(:,rid_e93,:) = 1.8e-10
      rate(:,rid_hk7a,:) = 1.2e-10
      rate(:,rid_hk7b,:) = 1.2e-10
      rate(:,rid_hk9,:) = 1.0e-20
      rate(:,rid_hk10,:) = 1.3e-16
      rate(:,rid_hk12,:) = 2.1e-15
      rate(:,rid_hk13,:) = 4.2e-13
      rate(:,rid_hk14,:) = 2.2e-11
      rate(:,rid_hk15,:) = 8.0e-14
      rate(:,rid_hk16,:) = 3.9e-17
      rate(:,rid_hk30,:) = 2.58e-04
      rate(:,rid_hk31,:) = 0.0758
      
!----------------------------------------------
!       ... Arrhenius law chemical reaction rates
!----------------------------------------------
      itemp(:) = 1. / temp(:)
      rate(:,rid_a2,lat) = 1.4e-10 * EXP( -470. * itemp(:) )
      rate(:,rid_a5,lat) = 2.2e-11 * EXP( 120. * itemp(:) )
      rate(:,rid_a6,lat) = 1.5e-12 * EXP( -880. * itemp(:) )
      rate(:,rid_a6b,lat) = 2.0e-14 * EXP( -680. * itemp(:) )
      rate(:,rid_a7,lat) = 3.e-11 * EXP( 200. * itemp(:) )
      rate(:,rid_a17,lat) = 4.8e-11 * EXP( 250. * itemp(:) )
      rate(:,rid_a19,lat) = 5.5e-12 * EXP( -2000. * itemp(:) )
      rate(:,rid_a24,lat) = 8.8e-12 * EXP( -4200. * itemp(:) )
      rate(:,rid_a26,lat) = 3.5e-12 * EXP( 250. * itemp(:) )
      rate(:,rid_a30,lat) = 2.9e-12 * EXP( -160. * itemp(:) )
      rate(:,rid_a81,lat) = 1.4e-12 * EXP( -2000. * itemp(:) )
      rate(:,rid_a82,lat) = 4.2e-12 * EXP( -240. * itemp(:) )
      rate(:,rid_b3,lat) = 5.6e-12 * EXP( 180. * itemp(:) )
      rate(:,rid_b4,lat) = 3.e-12 * EXP( -1500. * itemp(:) )
      rate(:,rid_b6,lat) = 2.1e-11 * EXP( 100. * itemp(:) )
      rate(:,rid_b7,lat) = 1.5e-11 * EXP( -3600. * itemp(:) )
      rate(:,rid_b9,lat) = 1.2e-13 * EXP( -2450. * itemp(:) )
      rate(:,rid_b28,lat) = 1.3e-12 * EXP( 380. * itemp(:) )
      rate(:,rid_b84,lat) = 1.5e-11 * EXP( 170. * itemp(:) )
      rate(:,rid_c2,lat) = 2.45e-12 * EXP( -1775. * itemp(:) )
      rate(:,rid_c3,lat) = 6.6e-33 * EXP( -1103. * itemp(:) )
      rate(:,rid_c5,lat) = 3.0e-12 * EXP( 280. * itemp(:) )
      rate(:,rid_c7,lat) = 3.8e-13 * EXP( 800. * itemp(:) )
      rate(:,rid_c9,lat) = 3.4e-11 * EXP( -1600. * itemp(:) )
      rate(:,rid_c10,lat) = 6.3e-13 * EXP( -2058. * itemp(:) )
      rate(:,rid_c17,lat) = 2.204e-12 * EXP( 200. * itemp(:) )
      rate(:,rid_c44,lat) = 1.596e-12 * EXP( 200. * itemp(:) )
      rate(:,rid_d0,lat) = 4.1e-12 * EXP( -1400. * itemp(:) )
      rate(:,rid_d1,lat) = 3.2e-11 * EXP( -1250. * itemp(:) )
      rate(:,rid_d2,lat) = 2.3e-11 * EXP( -200. * itemp(:) )
      rate(:,rid_d3,lat) = 3.0e-11 * EXP( 70. * itemp(:) )
      rate(:,rid_d4,lat) = 6.4e-12 * EXP( 290. * itemp(:) )
      rate(:,rid_d5,lat) = 9.6e-12 * EXP( -1360. * itemp(:) )
      rate(:,rid_d6,lat) = 3.7e-11 * EXP( -2300. * itemp(:) )
      rate(:,rid_d7,lat) = 1.8e-11 * EXP( 170. * itemp(:) )
      rate(:,rid_d8,lat) = 7.4e-12 * EXP( 270. * itemp(:) )
      rate(:,rid_d8a,lat) = 3.2e-13 * EXP( 320. * itemp(:) )
      rate(:,rid_d10,lat) = 8.1e-11 * EXP( -30. * itemp(:) )
      rate(:,rid_d11,lat) = 2.6e-12 * EXP( -350. * itemp(:) )
      rate(:,rid_d32,lat) = 2.9e-12 * EXP( -800. * itemp(:) )
      rate(:,rid_d33,lat) = 4.8e-13 * EXP( 700. * itemp(:) )
      rate(:,rid_d34,lat) = 3e-12 * EXP( -500. * itemp(:) )
      rate(:,rid_d37,lat) = 2.5e-12 * EXP( -130. * itemp(:) )
      rate(:,rid_d47,lat) = 3.5e-13 * EXP( -1370. * itemp(:) )
      rate(:,rid_d48,lat) = 1e-12 * EXP( -1590. * itemp(:) )
      rate(:,rid_d49,lat) = 3e-11 * EXP( -2450. * itemp(:) )
      rate(:,rid_d50,lat) = 1.8e-12 * EXP( -1550. * itemp(:) )
      rate(:,rid_d52,lat) = 1e-12 * EXP( -1600. * itemp(:) )
      rate(:,rid_d62,lat) = 4.5e-13 * EXP( 800. * itemp(:) )
      rate(:,rid_d63,lat) = 3.4e-11 * EXP( 160. * itemp(:) )
      rate(:,rid_d64,lat) = 2.4e-12 * EXP( -960. * itemp(:) )
      rate(:,rid_d65,lat) = 2.5e-12 * EXP( -600. * itemp(:) )
      rate(:,rid_d81,lat) = 1.4e-12 * EXP( -900. * itemp(:) )
      rate(:,rid_d82,lat) = 6.5e-12 * EXP( 135. * itemp(:) )
      rate(:,rid_d83,lat) = 4.1e-11 * EXP( -450. * itemp(:) )
      rate(:,rid_d84,lat) = 1.1e-11 * EXP( -980. * itemp(:) )
      rate(:,rid_d85,lat) = 1.e-11 * EXP( -3300. * itemp(:) )
      rate(:,rid_d87,lat) = 1.2e-12 * EXP( -330. * itemp(:) )
      rate(:,rid_e0,lat) = 4e-12 * EXP( -1470. * itemp(:) )
      rate(:,rid_e1,lat) = 1.6e-13 * EXP( -710. * itemp(:) )
      rate(:,rid_e2,lat) = 1.7e-11 * EXP( -800. * itemp(:) )
      rate(:,rid_e3,lat) = 1.9e-11 * EXP( 230. * itemp(:) )
      rate(:,rid_e4,lat) = 8.8e-12 * EXP( 260. * itemp(:) )
      rate(:,rid_e5a,lat) = 9.5e-13 * EXP( 550. * itemp(:) )
      rate(:,rid_e5b,lat) = 2.3e-12 * EXP( 260. * itemp(:) )
      rate(:,rid_e5c,lat) = 4.1e-13 * EXP( 290. * itemp(:) )
      rate(:,rid_e6,lat) = 1.5e-12 * EXP( 230. * itemp(:) )
      rate(:,rid_e7,lat) = 1.5e-11 * EXP( -600. * itemp(:) )
      rate(:,rid_e8,lat) = 2.6e-11 * EXP( -1300. * itemp(:) )
      rate(:,rid_e9,lat) = 1.7e-11 * EXP( -800. * itemp(:) )
      rate(:,rid_e15,lat) = 3.4e-12 * EXP( 540. * itemp(:) )
      rate(:,rid_e81,lat) = 5.8e-12 * EXP( -1500. * itemp(:) )
      rate(:,rid_hk3,lat) = 8.0e-12 * EXP( -2060. * itemp(:) )
      rate(:,rid_hk4,lat) = 1.8e-11 * EXP( 110. * itemp(:) )
      rate(:,rid_hk5a,lat) = 0.736e-11 * EXP( 70. * itemp(:) )
      rate(:,rid_hk5b,lat) = 2.464e-11 * EXP( 70. * itemp(:) )
      rate(:,rid_hk8,lat) = 3.6e-18 * EXP( -220. * itemp(:) )

      end subroutine SETRXT

