! subversion Id for THIS file : $Id: socpp-adjrxt.f 8506 2016-01-28 10:09:58Z simonc $
! $URL: http://svn-ae/ae/COMMON/stand-alone/atmos_models/socrates/tags/07.18.01/src/socpp-adjrxt.f $
!-----------------------------------------------------------------------
! DO NOT EDIT THIS FILE!! It was automatically written by
! the socpp program. Use that program and its *.in input file
! (see directory preproc/ ) to overwrite it
!============================================================

      subroutine ADJRXT( rate
     $,                  inv )

      use RXT_NAMES

      implicit none

!--------------------------------------------------------------------
!       ... Dummy args
!--------------------------------------------------------------------
      real, intent(in) ::      inv(121,2)
      real, intent(inout) ::   rate(121,202)


      rate(:,rid_a1) = rate(:,rid_a1) * inv(:,1)
      rate(:,rid_a83) = rate(:,rid_a83) * inv(:,1)
      rate(:,rid_b12) = rate(:,rid_b12) * inv(:,1)
      rate(:,rid_b22) = rate(:,rid_b22) * inv(:,1)
      rate(:,rid_b23) = rate(:,rid_b23) * inv(:,1)
      rate(:,rid_b24) = rate(:,rid_b24) * inv(:,1)
      rate(:,rid_b32) = rate(:,rid_b32) * inv(:,1)
      rate(:,rid_b81) = rate(:,rid_b81) * inv(:,1)
      rate(:,rid_b82) = rate(:,rid_b82) * inv(:,1)
      rate(:,rid_c3) = rate(:,rid_c3) * inv(:,1)
      rate(:,rid_d31) = rate(:,rid_d31) * inv(:,1)
      rate(:,rid_d36) = rate(:,rid_d36) * inv(:,1)
      rate(:,rid_d60) = rate(:,rid_d60) * inv(:,1)
      rate(:,rid_d61) = rate(:,rid_d61) * inv(:,1)
      rate(:,rid_e13) = rate(:,rid_e13) * inv(:,1)
      rate(:,rid_hk1) = rate(:,rid_hk1) * inv(:,1)
      rate(:,rid_hk2) = rate(:,rid_hk2) * inv(:,1)
      rate(:,rid_hk4) = rate(:,rid_hk4) * inv(:,2)
      rate(:,rid_hk9) = rate(:,rid_hk9) * inv(:,2)
      rate(:,rid_hk12) = rate(:,rid_hk12) * inv(:,2)
      rate(:,rid_hk21) = rate(:,rid_hk21) * inv(:,2) * inv(:,1)

      end subroutine ADJRXT
