! subversion Id for THIS file : $Id: socpp-imp_prod_loss.f 8506 2016-01-28 10:09:58Z simonc $
! $URL: http://svn-ae/ae/COMMON/stand-alone/atmos_models/socrates/tags/07.18.01/src/socpp-imp_prod_loss.f $
!-----------------------------------------------------------------------
! DO NOT EDIT THIS FILE!! It was automatically written by
! the socpp program. Use that program and its *.in input file
! (see directory preproc/ ) to overwrite it
!============================================================

      subroutine IMP_PROD_LOSS( prod
     $,                         loss
     $,                         y
     $,                         rxt
     $,                         het_rates
     $,                         converged
     $,                         kl, ku )
!--------------------------------------------------------------------
!       ... Production and loss for Implicit method
!--------------------------------------------------------------------

      use RXT_NAMES
      use SPC_NAMES


      implicit none

!--------------------------------------------------------------------
!     ... Dummy arguments
!--------------------------------------------------------------------
      integer, intent(in)   ::  kl, ku
      real, intent(out)   ::  prod(4,56)
      real, intent(out)   ::  loss(4,56)
      real, intent(in)    ::  y(4,56)
      real, intent(in)    ::  rxt(4,202)
      real, intent(in)    ::  het_rates(4,7)
      logical, intent(in)   ::  converged(4)

!--------------------------------------------------------------------
!     ... Local variables
!--------------------------------------------------------------------
      integer ::  k

      do k = kl,ku
         if( .not. converged(k) ) then
            loss(k,12) = ((rxt(k,rid_b38) +rxt(k,rid_b39))
     $           *y(k,vid_o1d) + rxt(k,rid_jn2o))*y(k,vid_n2o)
            prod(k,12) =rxt(k,rid_hk21)*y(k,vid_o1d)
            loss(k,33) = ((rxt(k,rid_c1) +rxt(k,rid_c1a) +
     $           rxt(k,rid_c1b))*y(k,vid_o1d) +rxt(k,rid_c2)
     $           *y(k,vid_oh) +rxt(k,rid_d5)*y(k,vid_cl)
     $            + rxt(k,rid_jch4))*y(k,vid_ch4)
            prod(k,33) = 0.
            loss(k,36) = (rxt(k,rid_a1et)*y(k,vid_o1d)
     $            + rxt(k,rid_jh2o))*y(k,vid_h2o)
            prod(k,36) = (rxt(k,rid_a17)*y(k,vid_ho2) +
     $           rxt(k,rid_a19)*y(k,vid_h2) +
     $           rxt(k,rid_a30)*y(k,vid_h2o2) +
     $           rxt(k,rid_a82)*y(k,vid_oh) +
     $           rxt(k,rid_b27)*y(k,vid_hno3) +
     $           rxt(k,rid_b28)*y(k,vid_ho2no2) +
     $           rxt(k,rid_c2)*y(k,vid_ch4) +
     $           rxt(k,rid_c8)*y(k,vid_ch2o) +
     $           rxt(k,rid_c17)*y(k,vid_ch3ooh) +
     $           rxt(k,rid_c44)*y(k,vid_ch3ooh) +
     $           rxt(k,rid_d0)*y(k,vid_ch3cl) +
     $           rxt(k,rid_d11)*y(k,vid_hcl) +
     $           rxt(k,rid_d34)*y(k,vid_hocl) +
     $           rxt(k,rid_d50)*y(k,vid_ch3ccl3) +
     $           rxt(k,rid_d52)*y(k,vid_hcfc22) +
     $           rxt(k,rid_e0)*y(k,vid_ch3br) +
     $           rxt(k,rid_e1)*y(k,vid_chbr3) +
     $           rxt(k,rid_e11)*y(k,vid_hbr))*y(k,vid_oh)
     $            +rxt(k,rid_a23c)*y(k,vid_ho2)*y(k,vid_h)
            loss(k,31) = (rxt(k,rid_c3)*y(k,vid_o3p) +rxt(k,rid_a36)
     $           *y(k,vid_oh))*y(k,vid_co)
            prod(k,31) = (rxt(k,rid_jch2o_h) +rxt(k,rid_jch2o_h2) +
     $           rxt(k,rid_c8)*y(k,vid_oh) +
     $           rxt(k,rid_c9)*y(k,vid_o3p) +
     $           rxt(k,rid_c10)*y(k,vid_no3) +
     $           rxt(k,rid_d10)*y(k,vid_cl) +
     $           rxt(k,rid_e9)*y(k,vid_br))*y(k,vid_ch2o)
     $            +rxt(k,rid_jco2)*y(k,vid_co2)
     $            +rxt(k,rid_d1)*y(k,vid_cl)*y(k,vid_ch3cl)
            loss(k,40) = (rxt(k,rid_d85)*y(k,vid_o3p)
     $            +rxt(k,rid_d75)*y(k,vid_o1d) +rxt(k,rid_d11)
     $           *y(k,vid_oh) + (rxt(k,rid_het5) +
     $           rxt(k,rid_PMChet5))*y(k,vid_hocl)
     $            + (rxt(k,rid_het2) +rxt(k,rid_PMChet2))
     $           *y(k,vid_clono2) + (rxt(k,rid_het4) +
     $           rxt(k,rid_PMChet4))*y(k,vid_n2o5) + rxt(k,rid_jhcl)
     $            + het_rates(k,4))*y(k,vid_hcl)
            prod(k,40) = (2.000*rxt(k,rid_d1)*y(k,vid_ch3cl) +
     $           rxt(k,rid_d5)*y(k,vid_ch4) +
     $           rxt(k,rid_d6)*y(k,vid_h2) +
     $           rxt(k,rid_d7)*y(k,vid_ho2) +
     $           rxt(k,rid_d10)*y(k,vid_ch2o) +
     $           rxt(k,rid_d84)*y(k,vid_h2o2))*y(k,vid_cl)
     $            + (rxt(k,rid_d8a)*y(k,vid_oh) +
     $           rxt(k,rid_d33a)*y(k,vid_ho2))*y(k,vid_clo)
            loss(k,32) = (rxt(k,rid_e81)*y(k,vid_o3p)
     $            +rxt(k,rid_e71)*y(k,vid_o1d) +rxt(k,rid_e11)
     $           *y(k,vid_oh) + het_rates(k,7))*y(k,vid_hbr)
            prod(k,32) = (rxt(k,rid_e7)*y(k,vid_ho2) +
     $           rxt(k,rid_e9)*y(k,vid_ch2o))*y(k,vid_br)
            loss(k,23) = ( + rxt(k,rid_jco2))*y(k,vid_co2)
            prod(k,23) = (rxt(k,rid_a36)*y(k,vid_oh) +
     $           rxt(k,rid_c3)*y(k,vid_o3p))*y(k,vid_co)
            loss(k,37) = (rxt(k,rid_a24)*y(k,vid_o3p)
     $            +rxt(k,rid_a3et)*y(k,vid_o1d) +rxt(k,rid_a19)
     $           *y(k,vid_oh) +rxt(k,rid_d6)*y(k,vid_cl))
     $           *y(k,vid_h2)
            prod(k,37) =rxt(k,rid_c1a)*y(k,vid_o1d)*y(k,vid_ch4)
     $            +rxt(k,rid_jch2o_h2)*y(k,vid_ch2o)
     $            +rxt(k,rid_a23b)*y(k,vid_ho2)*y(k,vid_h)
            loss(k,41) = (rxt(k,rid_c9)*y(k,vid_o3p) +rxt(k,rid_c8)
     $           *y(k,vid_oh) +rxt(k,rid_d10)*y(k,vid_cl)
     $            +rxt(k,rid_c10)*y(k,vid_no3) +rxt(k,rid_e9)
     $           *y(k,vid_br) + rxt(k,rid_jch2o_h)
     $            + rxt(k,rid_jch2o_h2) + het_rates(k,6))
     $           *y(k,vid_ch2o)
            prod(k,41) = (rxt(k,rid_c1a)*y(k,vid_o1d) +
     $           rxt(k,rid_c1b)*y(k,vid_o1d))*y(k,vid_ch4)
     $            + (rxt(k,rid_jch3ooh) +rxt(k,rid_c44)*y(k,vid_oh))
     $           *y(k,vid_ch3ooh) +rxt(k,rid_c5)*y(k,vid_ch3o2)
     $           *y(k,vid_no)
            loss(k,3) = (rxt(k,rid_d101)*y(k,vid_o1d)
     $            + rxt(k,rid_jcfc10))*y(k,vid_cfc10)
            prod(k,3) = 0.
            loss(k,4) = (rxt(k,rid_d102)*y(k,vid_o1d)
     $            + rxt(k,rid_jcfc11))*y(k,vid_cfc11)
            prod(k,4) = 0.
            loss(k,5) = (rxt(k,rid_d103)*y(k,vid_o1d)
     $            + rxt(k,rid_jcfc12))*y(k,vid_cfc12)
            prod(k,5) = 0.
            loss(k,6) = (rxt(k,rid_d104)*y(k,vid_o1d)
     $            + rxt(k,rid_jcfc113))*y(k,vid_cfc113)
            prod(k,6) = 0.
            loss(k,7) = (rxt(k,rid_d105)*y(k,vid_o1d)
     $            + rxt(k,rid_jcfc114))*y(k,vid_cfc114)
            prod(k,7) = 0.
            loss(k,8) = (rxt(k,rid_d106)*y(k,vid_o1d)
     $            + rxt(k,rid_jcfc115))*y(k,vid_cfc115)
            prod(k,8) = 0.
            loss(k,22) = (rxt(k,rid_d107)*y(k,vid_o1d)
     $            +rxt(k,rid_d52)*y(k,vid_oh) + rxt(k,rid_jhcfc22))
     $           *y(k,vid_hcfc22)
            prod(k,22) = 0.
            loss(k,10) = (rxt(k,rid_d50)*y(k,vid_oh)
     $            + rxt(k,rid_jch3ccl3))*y(k,vid_ch3ccl3)
            prod(k,10) = 0.
            loss(k,25) = (rxt(k,rid_d0)*y(k,vid_oh) +rxt(k,rid_d1)
     $           *y(k,vid_cl) + rxt(k,rid_jch3cl))*y(k,vid_ch3cl)
            prod(k,25) = 0.
            loss(k,11) = (rxt(k,rid_e92)*y(k,vid_o1d)
     $            + rxt(k,rid_jha1211))*y(k,vid_ha1211)
            prod(k,11) = 0.
            loss(k,9) = (rxt(k,rid_e91)*y(k,vid_o1d)
     $            + rxt(k,rid_jha1301))*y(k,vid_ha1301)
            prod(k,9) = 0.
            loss(k,1) = 0.
            prod(k,1) = (rxt(k,rid_d102)*y(k,vid_cfc11) +
     $           2.000*rxt(k,rid_d103)*y(k,vid_cfc12) +
     $           3.000*rxt(k,rid_d104)*y(k,vid_cfc113) +
     $           4.000*rxt(k,rid_d105)*y(k,vid_cfc114) +
     $           5.000*rxt(k,rid_d106)*y(k,vid_cfc115) +
     $           2.000*rxt(k,rid_d107)*y(k,vid_hcfc22) +
     $           3.000*rxt(k,rid_e91)*y(k,vid_ha1301) +
     $           2.000*rxt(k,rid_e92)*y(k,vid_ha1211))*y(k,vid_o1d)
     $            +3.000*rxt(k,rid_jcfc113)*y(k,vid_cfc113)
     $            +4.000*rxt(k,rid_jcfc114)*y(k,vid_cfc114)
     $            +5.000*rxt(k,rid_jcfc115)*y(k,vid_cfc115)
     $            +2.000*rxt(k,rid_jhcfc22)*y(k,vid_hcfc22)
     $            +2.000*rxt(k,rid_jha1211)*y(k,vid_ha1211)
     $            +3.000*rxt(k,rid_jha1301)*y(k,vid_ha1301)
            loss(k,24) = (rxt(k,rid_e93)*y(k,vid_o1d) +rxt(k,rid_e0)
     $           *y(k,vid_oh) + rxt(k,rid_jch3br))*y(k,vid_ch3br)
            prod(k,24) = 0.
            loss(k,13) = (rxt(k,rid_e1)*y(k,vid_oh)
     $            + rxt(k,rid_jchbr3))*y(k,vid_chbr3)
            prod(k,13) = 0.
            loss(k,54) = (rxt(k,rid_hk3)*y(k,vid_o3p)
     $            + (rxt(k,rid_hk7a) +rxt(k,rid_hk7b))*y(k,vid_o1d)
     $            +rxt(k,rid_a2)*y(k,vid_h) +rxt(k,rid_a6)
     $           *y(k,vid_oh) +rxt(k,rid_a6b)*y(k,vid_ho2)
     $            +rxt(k,rid_d2)*y(k,vid_cl) +rxt(k,rid_b4)
     $           *y(k,vid_no) +rxt(k,rid_b9)*y(k,vid_no2)
     $            +rxt(k,rid_e2)*y(k,vid_br) + rxt(k,rid_jo3_op)
     $            + rxt(k,rid_jo3_od))*y(k,vid_o3)
            prod(k,54) =rxt(k,rid_hk2)*y(k,vid_o2)*y(k,vid_o3p)
     $            +rxt(k,rid_d33a)*y(k,vid_clo)*y(k,vid_ho2)
            loss(k,51) = (rxt(k,rid_c3)*y(k,vid_co) +rxt(k,rid_d85)
     $           *y(k,vid_hcl) +rxt(k,rid_e81)*y(k,vid_hbr)
     $            +rxt(k,rid_a24)*y(k,vid_h2) +rxt(k,rid_c9)
     $           *y(k,vid_ch2o) +rxt(k,rid_hk3)*y(k,vid_o3)
     $            + 2.*rxt(k,rid_hk1)*y(k,vid_o3p) +rxt(k,rid_a5)
     $           *y(k,vid_oh) +rxt(k,rid_a7)*y(k,vid_ho2)
     $            +rxt(k,rid_a81)*y(k,vid_h2o2) +rxt(k,rid_d3)
     $           *y(k,vid_clo) +rxt(k,rid_d64)*y(k,vid_oclo)
     $            +rxt(k,rid_d35)*y(k,vid_hocl) +rxt(k,rid_d32)
     $           *y(k,vid_clono2) +rxt(k,rid_b82)*y(k,vid_no)
     $            + (rxt(k,rid_b3) +rxt(k,rid_b81))*y(k,vid_no2)
     $            +rxt(k,rid_b71)*y(k,vid_no3) +rxt(k,rid_e3)
     $           *y(k,vid_bro) +rxt(k,rid_hk2)*y(k,vid_o2))
     $           *y(k,vid_o3p)
            prod(k,51) = (2.000*rxt(k,rid_jo2_op) +
     $           rxt(k,rid_jo2_od) +rxt(k,rid_b7)*y(k,vid_n) +
     $           rxt(k,rid_hk5a)*y(k,vid_o1d) +
     $           rxt(k,rid_hk5b)*y(k,vid_o1d))*y(k,vid_o2)
     $            + (rxt(k,rid_jo3_op) +
     $           2.000*rxt(k,rid_hk7b)*y(k,vid_o1d))*y(k,vid_o3)
     $            + (rxt(k,rid_jho2) +rxt(k,rid_a23c)*y(k,vid_h))
     $           *y(k,vid_ho2) + (rxt(k,rid_jno) +
     $           rxt(k,rid_b6)*y(k,vid_n))*y(k,vid_no)
     $            +rxt(k,rid_hk4)*y(k,vid_o1d)
     $            +rxt(k,rid_a82)*y(k,vid_oh)*y(k,vid_oh)
     $            +rxt(k,rid_joclo)*y(k,vid_oclo) +rxt(k,rid_jno2)
     $           *y(k,vid_no2) +rxt(k,rid_jno3_no2)*y(k,vid_no3)
     $            +rxt(k,rid_jbro)*y(k,vid_bro)
            loss(k,47) = ((rxt(k,rid_b38) +rxt(k,rid_b39))
     $           *y(k,vid_n2o) + (rxt(k,rid_c1) +rxt(k,rid_c1a) +
     $           rxt(k,rid_c1b))*y(k,vid_ch4) +rxt(k,rid_a1et)
     $           *y(k,vid_h2o) +rxt(k,rid_d75)*y(k,vid_hcl)
     $            +rxt(k,rid_e71)*y(k,vid_hbr) +rxt(k,rid_a3et)
     $           *y(k,vid_h2) +rxt(k,rid_d101)*y(k,vid_cfc10)
     $            +rxt(k,rid_d102)*y(k,vid_cfc11) +rxt(k,rid_d103)
     $           *y(k,vid_cfc12) +rxt(k,rid_d104)*y(k,vid_cfc113)
     $            +rxt(k,rid_d105)*y(k,vid_cfc114) +rxt(k,rid_d106)
     $           *y(k,vid_cfc115) +rxt(k,rid_d107)*y(k,vid_hcfc22)
     $            +rxt(k,rid_e92)*y(k,vid_ha1211) +rxt(k,rid_e91)
     $           *y(k,vid_ha1301) +rxt(k,rid_e93)*y(k,vid_ch3br)
     $            + (rxt(k,rid_hk7a) +rxt(k,rid_hk7b))*y(k,vid_o3)
     $            +rxt(k,rid_d71)*y(k,vid_cl2) + (rxt(k,rid_hk5a) +
     $           rxt(k,rid_hk5b))*y(k,vid_o2) + rxt(k,rid_hk4)
     $            + rxt(k,rid_hk21))*y(k,vid_o1d)
            prod(k,47) =rxt(k,rid_jn2o)*y(k,vid_n2o)
     $            +rxt(k,rid_jco2)*y(k,vid_co2) +rxt(k,rid_jo3_od)
     $           *y(k,vid_o3) +rxt(k,rid_jo2_od)*y(k,vid_o2)
            loss(k,52) = (rxt(k,rid_a2)*y(k,vid_o3)
     $            + (rxt(k,rid_a23a) +rxt(k,rid_a23b) +
     $           rxt(k,rid_a23c))*y(k,vid_ho2) +rxt(k,rid_a1)
     $           *y(k,vid_o2))*y(k,vid_h)
            prod(k,52) = (rxt(k,rid_a3et)*y(k,vid_o1d) +
     $           rxt(k,rid_a19)*y(k,vid_oh) +
     $           rxt(k,rid_a24)*y(k,vid_o3p) +
     $           rxt(k,rid_d6)*y(k,vid_cl))*y(k,vid_h2)
     $            + (rxt(k,rid_jch4) +rxt(k,rid_c1b)*y(k,vid_o1d))
     $           *y(k,vid_ch4) + (rxt(k,rid_a5)*y(k,vid_o3p) +
     $           rxt(k,rid_a36)*y(k,vid_co))*y(k,vid_oh)
     $            +rxt(k,rid_jh2o)*y(k,vid_h2o) +rxt(k,rid_jhcl)
     $           *y(k,vid_hcl) +rxt(k,rid_jch2o_h)*y(k,vid_ch2o)
            loss(k,46) = (rxt(k,rid_c2)*y(k,vid_ch4) +rxt(k,rid_a36)
     $           *y(k,vid_co) +rxt(k,rid_d11)*y(k,vid_hcl)
     $            +rxt(k,rid_e11)*y(k,vid_hbr) +rxt(k,rid_a19)
     $           *y(k,vid_h2) +rxt(k,rid_c8)*y(k,vid_ch2o)
     $            +rxt(k,rid_d52)*y(k,vid_hcfc22) +rxt(k,rid_d50)
     $           *y(k,vid_ch3ccl3) +rxt(k,rid_d0)*y(k,vid_ch3cl)
     $            +rxt(k,rid_e0)*y(k,vid_ch3br) +rxt(k,rid_e1)
     $           *y(k,vid_chbr3) +rxt(k,rid_a6)*y(k,vid_o3)
     $            +rxt(k,rid_a5)*y(k,vid_o3p) + 2.*(rxt(k,rid_a82) +
     $           rxt(k,rid_a83))*y(k,vid_oh) +rxt(k,rid_a17)
     $           *y(k,vid_ho2) +rxt(k,rid_a30)*y(k,vid_h2o2)
     $            +rxt(k,rid_d81)*y(k,vid_cl2) + (rxt(k,rid_d8) +
     $           rxt(k,rid_d8a))*y(k,vid_clo) +rxt(k,rid_d62)
     $           *y(k,vid_oclo) +rxt(k,rid_d34)*y(k,vid_hocl)
     $            +rxt(k,rid_d87)*y(k,vid_clono2) +rxt(k,rid_b22)
     $           *y(k,vid_no2) +rxt(k,rid_b72)*y(k,vid_no3)
     $            +rxt(k,rid_b27)*y(k,vid_hno3) +rxt(k,rid_b28)
     $           *y(k,vid_ho2no2) +rxt(k,rid_e72)*y(k,vid_bro)
     $            +rxt(k,rid_c17)*y(k,vid_ch3ooh))*y(k,vid_oh)
            prod(k,46) = (rxt(k,rid_a7)*y(k,vid_ho2) +
     $           rxt(k,rid_a24)*y(k,vid_h2) +
     $           rxt(k,rid_a81)*y(k,vid_h2o2) +
     $           rxt(k,rid_c9)*y(k,vid_ch2o) +
     $           rxt(k,rid_d35)*y(k,vid_hocl) +
     $           rxt(k,rid_d85)*y(k,vid_hcl) +
     $           rxt(k,rid_e81)*y(k,vid_hbr))*y(k,vid_o3p)
     $            + (rxt(k,rid_jho2) +rxt(k,rid_a6b)*y(k,vid_o3) +
     $           2.000*rxt(k,rid_a23a)*y(k,vid_h) +
     $           rxt(k,rid_a26)*y(k,vid_no) +
     $           rxt(k,rid_b73a)*y(k,vid_no3) +
     $           rxt(k,rid_d83)*y(k,vid_cl))*y(k,vid_ho2)
     $            + (2.000*rxt(k,rid_a1et)*y(k,vid_h2o) +
     $           rxt(k,rid_a3et)*y(k,vid_h2) +
     $           rxt(k,rid_c1)*y(k,vid_ch4) +
     $           rxt(k,rid_d75)*y(k,vid_hcl) +
     $           rxt(k,rid_e71)*y(k,vid_hbr))*y(k,vid_o1d)
     $            + (rxt(k,rid_jhocl) +rxt(k,rid_d37)*y(k,vid_cl))
     $           *y(k,vid_hocl) +rxt(k,rid_jh2o)*y(k,vid_h2o)
     $            +rxt(k,rid_a2)*y(k,vid_h)*y(k,vid_o3)
     $            +2.000*rxt(k,rid_jh2o2)*y(k,vid_h2o2)
     $            +rxt(k,rid_jhno3)*y(k,vid_hno3)
     $            +rxt(k,rid_jhno4_2)*y(k,vid_ho2no2)
     $            +rxt(k,rid_jhobr)*y(k,vid_hobr)
     $            +rxt(k,rid_jch3ooh)*y(k,vid_ch3ooh)
            loss(k,48) = (rxt(k,rid_a6b)*y(k,vid_o3) +rxt(k,rid_a7)
     $           *y(k,vid_o3p) + (rxt(k,rid_a23a) +rxt(k,rid_a23b) +
     $           rxt(k,rid_a23c))*y(k,vid_h) +rxt(k,rid_a17)
     $           *y(k,vid_oh) + 2.*rxt(k,rid_a27)*y(k,vid_ho2)
     $            + (rxt(k,rid_d7) +rxt(k,rid_d83))*y(k,vid_cl)
     $            + (rxt(k,rid_d33) +rxt(k,rid_d33a))*y(k,vid_clo)
     $            +rxt(k,rid_a26)*y(k,vid_no) +rxt(k,rid_b23)
     $           *y(k,vid_no2) + (rxt(k,rid_b73a) +rxt(k,rid_b73b))
     $           *y(k,vid_no3) +rxt(k,rid_e7)*y(k,vid_br)
     $            +rxt(k,rid_e15)*y(k,vid_bro) +rxt(k,rid_c7)
     $           *y(k,vid_ch3o2) + rxt(k,rid_jho2))*y(k,vid_ho2)
            prod(k,48) = (rxt(k,rid_a6)*y(k,vid_o3) +
     $           rxt(k,rid_a30)*y(k,vid_h2o2) +
     $           rxt(k,rid_b72)*y(k,vid_no3) +
     $           rxt(k,rid_c8)*y(k,vid_ch2o) +
     $           rxt(k,rid_d0)*y(k,vid_ch3cl) +
     $           rxt(k,rid_d8)*y(k,vid_clo) +
     $           rxt(k,rid_e0)*y(k,vid_ch3br) +
     $           rxt(k,rid_e72)*y(k,vid_bro))*y(k,vid_oh)
     $            + (rxt(k,rid_jch2o_h) +
     $           rxt(k,rid_c9)*y(k,vid_o3p) +
     $           rxt(k,rid_c10)*y(k,vid_no3) +
     $           rxt(k,rid_d10)*y(k,vid_cl) +
     $           rxt(k,rid_e9)*y(k,vid_br))*y(k,vid_ch2o)
     $            + (rxt(k,rid_a81)*y(k,vid_o3p) +
     $           rxt(k,rid_d84)*y(k,vid_cl))*y(k,vid_h2o2)
     $            + (rxt(k,rid_jhno4_1) +rxt(k,rid_b24))
     $           *y(k,vid_ho2no2) +rxt(k,rid_c1b)*y(k,vid_o1d)
     $           *y(k,vid_ch4) +rxt(k,rid_d1)*y(k,vid_cl)
     $           *y(k,vid_ch3cl) +rxt(k,rid_a1)*y(k,vid_o2)
     $           *y(k,vid_h) +rxt(k,rid_c5)*y(k,vid_ch3o2)
     $           *y(k,vid_no) +rxt(k,rid_jch3ooh)*y(k,vid_ch3ooh)
            loss(k,29) = (rxt(k,rid_a81)*y(k,vid_o3p)
     $            +rxt(k,rid_a30)*y(k,vid_oh) +rxt(k,rid_d84)
     $           *y(k,vid_cl) + rxt(k,rid_jh2o2) + het_rates(k,2))
     $           *y(k,vid_h2o2)
            prod(k,29) =rxt(k,rid_a83)*y(k,vid_oh)*y(k,vid_oh)
     $            +rxt(k,rid_a27)*y(k,vid_ho2)*y(k,vid_ho2)
            loss(k,50) = (rxt(k,rid_d5)*y(k,vid_ch4) +rxt(k,rid_d6)
     $           *y(k,vid_h2) +rxt(k,rid_d10)*y(k,vid_ch2o)
     $            +rxt(k,rid_d1)*y(k,vid_ch3cl) +rxt(k,rid_d2)
     $           *y(k,vid_o3) + (rxt(k,rid_d7) +rxt(k,rid_d83))
     $           *y(k,vid_ho2) +rxt(k,rid_d84)*y(k,vid_h2o2)
     $            +rxt(k,rid_d63)*y(k,vid_oclo) +rxt(k,rid_d37)
     $           *y(k,vid_hocl) +rxt(k,rid_d82)*y(k,vid_clono2)
     $            +rxt(k,rid_d36)*y(k,vid_no2) +rxt(k,rid_d73)
     $           *y(k,vid_no3))*y(k,vid_cl)
            prod(k,50) = (rxt(k,rid_d71)*y(k,vid_cl2) +
     $           rxt(k,rid_d75)*y(k,vid_hcl) +
     $           4.000*rxt(k,rid_d101)*y(k,vid_cfc10) +
     $           3.000*rxt(k,rid_d102)*y(k,vid_cfc11) +
     $           2.000*rxt(k,rid_d103)*y(k,vid_cfc12) +
     $           3.000*rxt(k,rid_d104)*y(k,vid_cfc113) +
     $           2.000*rxt(k,rid_d105)*y(k,vid_cfc114) +
     $           rxt(k,rid_d106)*y(k,vid_cfc115) +
     $           rxt(k,rid_d107)*y(k,vid_hcfc22) +
     $           rxt(k,rid_e92)*y(k,vid_ha1211))*y(k,vid_o1d)
     $            + (rxt(k,rid_d3)*y(k,vid_o3p) +
     $           rxt(k,rid_d4)*y(k,vid_no) +
     $           rxt(k,rid_d8)*y(k,vid_oh) +
     $           rxt(k,rid_d47)*y(k,vid_clo) +
     $           2.000*rxt(k,rid_d49)*y(k,vid_clo) +
     $           rxt(k,rid_d74)*y(k,vid_no3) +
     $           rxt(k,rid_e5b)*y(k,vid_bro))*y(k,vid_clo)
     $            + (rxt(k,rid_d0)*y(k,vid_ch3cl) +
     $           rxt(k,rid_d11)*y(k,vid_hcl) +
     $           3.000*rxt(k,rid_d50)*y(k,vid_ch3ccl3) +
     $           rxt(k,rid_d52)*y(k,vid_hcfc22) +
     $           rxt(k,rid_d81)*y(k,vid_cl2))*y(k,vid_oh)
     $            + (rxt(k,rid_jhcl) +rxt(k,rid_d85)*y(k,vid_o3p))
     $           *y(k,vid_hcl) +4.000*rxt(k,rid_jcfc10)
     $           *y(k,vid_cfc10) +3.000*rxt(k,rid_jcfc11)
     $           *y(k,vid_cfc11) +2.000*rxt(k,rid_jcfc12)
     $           *y(k,vid_cfc12) +3.000*rxt(k,rid_jcfc113)
     $           *y(k,vid_cfc113) +2.000*rxt(k,rid_jcfc114)
     $           *y(k,vid_cfc114) +rxt(k,rid_jcfc115)
     $           *y(k,vid_cfc115) +rxt(k,rid_jhcfc22)
     $           *y(k,vid_hcfc22) +3.000*rxt(k,rid_jch3ccl3)
     $           *y(k,vid_ch3ccl3) +rxt(k,rid_jch3cl)*y(k,vid_ch3cl)
     $            +rxt(k,rid_jha1211)*y(k,vid_ha1211)
     $            +2.000*rxt(k,rid_jcl2)*y(k,vid_cl2)
     $            +rxt(k,rid_jhocl)*y(k,vid_hocl)
     $            +rxt(k,rid_jclno4_2)*y(k,vid_clono2)
     $            +rxt(k,rid_jclno2)*y(k,vid_clno2)
     $            +2.000*rxt(k,rid_jcl2o2)*y(k,vid_cl2o2)
     $            +rxt(k,rid_jbrcl)*y(k,vid_brcl)
            loss(k,34) = (rxt(k,rid_d71)*y(k,vid_o1d)
     $            +rxt(k,rid_d81)*y(k,vid_oh) + rxt(k,rid_jcl2))
     $           *y(k,vid_cl2)
            prod(k,34) = (rxt(k,rid_het2)*y(k,vid_clono2) +
     $           rxt(k,rid_het5)*y(k,vid_hocl) +
     $           rxt(k,rid_PMChet2)*y(k,vid_clono2) +
     $           rxt(k,rid_PMChet5)*y(k,vid_hocl))*y(k,vid_hcl)
     $            + (rxt(k,rid_d37)*y(k,vid_hocl) +
     $           rxt(k,rid_d72)*y(k,vid_cl2o2) +
     $           rxt(k,rid_d82)*y(k,vid_clono2))*y(k,vid_cl)
     $            +rxt(k,rid_d48)*y(k,vid_clo)*y(k,vid_clo)
            loss(k,56) = (rxt(k,rid_d3)*y(k,vid_o3p)
     $            + (rxt(k,rid_d8) +rxt(k,rid_d8a))*y(k,vid_oh)
     $            + (rxt(k,rid_d33) +rxt(k,rid_d33a))*y(k,vid_ho2)
     $            + 2.*(rxt(k,rid_d47) +rxt(k,rid_d48) +
     $           rxt(k,rid_d49) +rxt(k,rid_d60))*y(k,vid_clo)
     $            +rxt(k,rid_d4)*y(k,vid_no) +rxt(k,rid_d31)
     $           *y(k,vid_no2) +rxt(k,rid_d74)*y(k,vid_no3)
     $            + (rxt(k,rid_e5a) +rxt(k,rid_e5b) +rxt(k,rid_e5c))
     $           *y(k,vid_bro))*y(k,vid_clo)
            prod(k,56) = (rxt(k,rid_joclo) +
     $           2.000*rxt(k,rid_d63)*y(k,vid_cl) +
     $           rxt(k,rid_d64)*y(k,vid_o3p) +
     $           rxt(k,rid_d65)*y(k,vid_no) +
     $           rxt(k,rid_e8)*y(k,vid_br))*y(k,vid_oclo)
     $            + (rxt(k,rid_d32)*y(k,vid_clono2) +
     $           rxt(k,rid_d35)*y(k,vid_hocl))*y(k,vid_o3p)
     $            + (rxt(k,rid_d2)*y(k,vid_o3) +
     $           rxt(k,rid_d73)*y(k,vid_no3))*y(k,vid_cl)
     $            +rxt(k,rid_d71)*y(k,vid_cl2)*y(k,vid_o1d)
     $            +rxt(k,rid_d34)*y(k,vid_hocl)*y(k,vid_oh)
     $            +rxt(k,rid_jclno4_1)*y(k,vid_clono2)
     $            +2.000*rxt(k,rid_d61)*y(k,vid_cl2o2)
            loss(k,43) = (rxt(k,rid_d64)*y(k,vid_o3p)
     $            +rxt(k,rid_d62)*y(k,vid_oh) +rxt(k,rid_d63)
     $           *y(k,vid_cl) +rxt(k,rid_d65)*y(k,vid_no)
     $            +rxt(k,rid_e8)*y(k,vid_br) + rxt(k,rid_joclo))
     $           *y(k,vid_oclo)
            prod(k,43) = (rxt(k,rid_d47)*y(k,vid_clo) +
     $           rxt(k,rid_e5a)*y(k,vid_bro))*y(k,vid_clo)
     $            +rxt(k,rid_d83)*y(k,vid_cl)*y(k,vid_ho2)
            loss(k,39) = ((rxt(k,rid_het5) +rxt(k,rid_PMChet5))
     $           *y(k,vid_hcl) +rxt(k,rid_d35)*y(k,vid_o3p)
     $            +rxt(k,rid_d34)*y(k,vid_oh) +rxt(k,rid_d37)
     $           *y(k,vid_cl) + rxt(k,rid_jhocl))*y(k,vid_hocl)
            prod(k,39) = (rxt(k,rid_g1) +rxt(k,rid_het1) +
     $           rxt(k,rid_PMChet1) +rxt(k,rid_d87)*y(k,vid_oh))
     $           *y(k,vid_clono2) + (rxt(k,rid_d62)*y(k,vid_oclo) +
     $           rxt(k,rid_d81)*y(k,vid_cl2))*y(k,vid_oh)
     $            +rxt(k,rid_d33)*y(k,vid_clo)*y(k,vid_ho2)
            loss(k,38) = ((rxt(k,rid_het2) +rxt(k,rid_PMChet2))
     $           *y(k,vid_hcl) +rxt(k,rid_d32)*y(k,vid_o3p)
     $            +rxt(k,rid_d87)*y(k,vid_oh) +rxt(k,rid_d82)
     $           *y(k,vid_cl) + rxt(k,rid_jclno4_1)
     $            + rxt(k,rid_jclno4_2) + rxt(k,rid_g1)
     $            + rxt(k,rid_het1) + rxt(k,rid_PMChet1))
     $           *y(k,vid_clono2)
            prod(k,38) =rxt(k,rid_d31)*y(k,vid_no2)*y(k,vid_clo)
            loss(k,19) = ( + rxt(k,rid_jclno2))*y(k,vid_clno2)
            prod(k,19) = (rxt(k,rid_het4)*y(k,vid_n2o5) +
     $           rxt(k,rid_PMChet4)*y(k,vid_n2o5))*y(k,vid_hcl)
     $            +rxt(k,rid_d36)*y(k,vid_no2)*y(k,vid_cl)
            loss(k,20) = (rxt(k,rid_d72)*y(k,vid_cl)
     $            + rxt(k,rid_jcl2o2) + rxt(k,rid_d61))
     $           *y(k,vid_cl2o2)
            prod(k,20) =rxt(k,rid_d60)*y(k,vid_clo)*y(k,vid_clo)
            loss(k,18) = (rxt(k,rid_b6)*y(k,vid_no) +rxt(k,rid_b7)
     $           *y(k,vid_o2))*y(k,vid_n)
            prod(k,18) =rxt(k,rid_jno)*y(k,vid_no)
            loss(k,49) = (rxt(k,rid_b4)*y(k,vid_o3) +rxt(k,rid_b82)
     $           *y(k,vid_o3p) +rxt(k,rid_a26)*y(k,vid_ho2)
     $            +rxt(k,rid_d4)*y(k,vid_clo) +rxt(k,rid_d65)
     $           *y(k,vid_oclo) +rxt(k,rid_b6)*y(k,vid_n)
     $            +rxt(k,rid_b84)*y(k,vid_no3) +rxt(k,rid_e4)
     $           *y(k,vid_bro) +rxt(k,rid_c5)*y(k,vid_ch3o2)
     $            + rxt(k,rid_jno))*y(k,vid_no)
            prod(k,49) = (rxt(k,rid_jno2) +
     $           rxt(k,rid_b3)*y(k,vid_o3p))*y(k,vid_no2)
     $            +2.000*rxt(k,rid_b39)*y(k,vid_o1d)*y(k,vid_n2o)
     $            +rxt(k,rid_b7)*y(k,vid_o2)*y(k,vid_n)
     $            +rxt(k,rid_jno3_no)*y(k,vid_no3)
            loss(k,55) = (rxt(k,rid_b9)*y(k,vid_o3)
     $            + (rxt(k,rid_b3) +rxt(k,rid_b81))*y(k,vid_o3p)
     $            +rxt(k,rid_b22)*y(k,vid_oh) +rxt(k,rid_b23)
     $           *y(k,vid_ho2) +rxt(k,rid_d36)*y(k,vid_cl)
     $            +rxt(k,rid_d31)*y(k,vid_clo) +rxt(k,rid_b12)
     $           *y(k,vid_no3) +rxt(k,rid_e13)*y(k,vid_bro)
     $            + rxt(k,rid_jno2))*y(k,vid_no2)
            prod(k,55) = (rxt(k,rid_a26)*y(k,vid_ho2) +
     $           rxt(k,rid_b4)*y(k,vid_o3) +
     $           rxt(k,rid_b82)*y(k,vid_o3p) +
     $           2.000*rxt(k,rid_b84)*y(k,vid_no3) +
     $           rxt(k,rid_c5)*y(k,vid_ch3o2) +
     $           rxt(k,rid_d4)*y(k,vid_clo) +
     $           rxt(k,rid_d65)*y(k,vid_oclo) +
     $           rxt(k,rid_e4)*y(k,vid_bro))*y(k,vid_no)
     $            + (rxt(k,rid_jno3_no2) +
     $           rxt(k,rid_b71)*y(k,vid_o3p) +
     $           rxt(k,rid_b72)*y(k,vid_oh) +
     $           rxt(k,rid_b73a)*y(k,vid_ho2) +
     $           rxt(k,rid_d73)*y(k,vid_cl) +
     $           rxt(k,rid_d74)*y(k,vid_clo))*y(k,vid_no3)
     $            + (rxt(k,rid_jhno4_1) +rxt(k,rid_b24) +
     $           rxt(k,rid_b28)*y(k,vid_oh))*y(k,vid_ho2no2)
     $            + (rxt(k,rid_jn2o5) +rxt(k,rid_b32))*y(k,vid_n2o5)
     $            +rxt(k,rid_jclno4_1)*y(k,vid_clono2)
     $            +rxt(k,rid_jclno2)*y(k,vid_clno2)
     $            +rxt(k,rid_jhno3)*y(k,vid_hno3)
     $            +.710*rxt(k,rid_jbrono2)*y(k,vid_brono2)
            loss(k,53) = (rxt(k,rid_c10)*y(k,vid_ch2o)
     $            +rxt(k,rid_b71)*y(k,vid_o3p) +rxt(k,rid_b72)
     $           *y(k,vid_oh) + (rxt(k,rid_b73a) +rxt(k,rid_b73b))
     $           *y(k,vid_ho2) +rxt(k,rid_d73)*y(k,vid_cl)
     $            +rxt(k,rid_d74)*y(k,vid_clo) +rxt(k,rid_b84)
     $           *y(k,vid_no) +rxt(k,rid_b12)*y(k,vid_no2)
     $            + rxt(k,rid_jno3_no2) + rxt(k,rid_jno3_no))
     $           *y(k,vid_no3)
            prod(k,53) = (rxt(k,rid_jclno4_2) +
     $           rxt(k,rid_d32)*y(k,vid_o3p) +
     $           rxt(k,rid_d82)*y(k,vid_cl) +
     $           rxt(k,rid_d87)*y(k,vid_oh))*y(k,vid_clono2)
     $            + (rxt(k,rid_b9)*y(k,vid_o3) +
     $           rxt(k,rid_b81)*y(k,vid_o3p))*y(k,vid_no2)
     $            + (rxt(k,rid_jn2o5) +rxt(k,rid_b32))*y(k,vid_n2o5)
     $            +rxt(k,rid_b27)*y(k,vid_hno3)*y(k,vid_oh)
     $            +rxt(k,rid_jhno4_2)*y(k,vid_ho2no2)
     $            +.290*rxt(k,rid_jbrono2)*y(k,vid_brono2)
            loss(k,30) = (rxt(k,rid_b27)*y(k,vid_oh)
     $            + rxt(k,rid_jhno3) + het_rates(k,1))*y(k,vid_hno3)
            prod(k,30) = (rxt(k,rid_g1) +rxt(k,rid_het1) +
     $           rxt(k,rid_PMChet1) +rxt(k,rid_het2)*y(k,vid_hcl) +
     $           rxt(k,rid_PMChet2)*y(k,vid_hcl))*y(k,vid_clono2)
     $            + (2.000*rxt(k,rid_g2) +2.000*rxt(k,rid_het3) +
     $           2.000*rxt(k,rid_PMChet3) +
     $           rxt(k,rid_het4)*y(k,vid_hcl) +
     $           rxt(k,rid_PMChet4)*y(k,vid_hcl))*y(k,vid_n2o5)
     $            + (rxt(k,rid_b73b)*y(k,vid_ho2) +
     $           rxt(k,rid_c10)*y(k,vid_ch2o))*y(k,vid_no3)
     $            +rxt(k,rid_b22)*y(k,vid_no2)*y(k,vid_oh)
            loss(k,26) = ((rxt(k,rid_het4) +rxt(k,rid_PMChet4))
     $           *y(k,vid_hcl) + rxt(k,rid_jn2o5) + rxt(k,rid_b32)
     $            + rxt(k,rid_g2) + rxt(k,rid_het3)
     $            + rxt(k,rid_PMChet3))*y(k,vid_n2o5)
            prod(k,26) =rxt(k,rid_b12)*y(k,vid_no3)*y(k,vid_no2)
            loss(k,28) = (rxt(k,rid_b28)*y(k,vid_oh)
     $            + rxt(k,rid_jhno4_1) + rxt(k,rid_jhno4_2)
     $            + rxt(k,rid_b24) + het_rates(k,5))*y(k,vid_ho2no2)
            prod(k,28) =rxt(k,rid_b23)*y(k,vid_no2)*y(k,vid_ho2)
            loss(k,45) = (rxt(k,rid_e9)*y(k,vid_ch2o) +rxt(k,rid_e2)
     $           *y(k,vid_o3) +rxt(k,rid_e7)*y(k,vid_ho2)
     $            +rxt(k,rid_e8)*y(k,vid_oclo))*y(k,vid_br)
            prod(k,45) = (rxt(k,rid_jbro) +
     $           rxt(k,rid_e3)*y(k,vid_o3p) +
     $           rxt(k,rid_e4)*y(k,vid_no) +
     $           rxt(k,rid_e5a)*y(k,vid_clo) +
     $           rxt(k,rid_e5b)*y(k,vid_clo) +
     $           2.000*rxt(k,rid_e6)*y(k,vid_bro) +
     $           rxt(k,rid_e72)*y(k,vid_oh))*y(k,vid_bro)
     $            + (rxt(k,rid_e71)*y(k,vid_hbr) +
     $           rxt(k,rid_e91)*y(k,vid_ha1301) +
     $           rxt(k,rid_e92)*y(k,vid_ha1211) +
     $           rxt(k,rid_e93)*y(k,vid_ch3br))*y(k,vid_o1d)
     $            + (rxt(k,rid_e0)*y(k,vid_ch3br) +
     $           3.000*rxt(k,rid_e1)*y(k,vid_chbr3) +
     $           rxt(k,rid_e11)*y(k,vid_hbr))*y(k,vid_oh)
     $            +rxt(k,rid_e81)*y(k,vid_o3p)*y(k,vid_hbr)
     $            +rxt(k,rid_jha1211)*y(k,vid_ha1211)
     $            +rxt(k,rid_jha1301)*y(k,vid_ha1301)
     $            +rxt(k,rid_jch3br)*y(k,vid_ch3br)
     $            +3.000*rxt(k,rid_jchbr3)*y(k,vid_chbr3)
     $            +rxt(k,rid_jhobr)*y(k,vid_hobr)
     $            +.290*rxt(k,rid_jbrono2)*y(k,vid_brono2)
     $            +rxt(k,rid_jbrcl)*y(k,vid_brcl)
            loss(k,44) = (rxt(k,rid_e3)*y(k,vid_o3p) +rxt(k,rid_e72)
     $           *y(k,vid_oh) +rxt(k,rid_e15)*y(k,vid_ho2)
     $            + (rxt(k,rid_e5a) +rxt(k,rid_e5b) +rxt(k,rid_e5c))
     $           *y(k,vid_clo) +rxt(k,rid_e4)*y(k,vid_no)
     $            +rxt(k,rid_e13)*y(k,vid_no2) + 2.*rxt(k,rid_e6)
     $           *y(k,vid_bro) + rxt(k,rid_jbro))*y(k,vid_bro)
            prod(k,44) = (rxt(k,rid_e2)*y(k,vid_o3) +
     $           rxt(k,rid_e8)*y(k,vid_oclo))*y(k,vid_br)
     $            +.710*rxt(k,rid_jbrono2)*y(k,vid_brono2)
            loss(k,14) = ( + rxt(k,rid_jhobr))*y(k,vid_hobr)
            prod(k,14) =rxt(k,rid_e15)*y(k,vid_bro)*y(k,vid_ho2)
            loss(k,21) = ( + rxt(k,rid_jbrono2))*y(k,vid_brono2)
            prod(k,21) =rxt(k,rid_e13)*y(k,vid_bro)*y(k,vid_no2)
            loss(k,15) = ( + rxt(k,rid_jbrcl))*y(k,vid_brcl)
            prod(k,15) =rxt(k,rid_e5c)*y(k,vid_bro)*y(k,vid_clo)
            loss(k,35) = (rxt(k,rid_c7)*y(k,vid_ho2) +rxt(k,rid_c5)
     $           *y(k,vid_no))*y(k,vid_ch3o2)
            prod(k,35) = (rxt(k,rid_jch4) +
     $           rxt(k,rid_c1)*y(k,vid_o1d) +
     $           rxt(k,rid_c2)*y(k,vid_oh) +
     $           rxt(k,rid_d5)*y(k,vid_cl))*y(k,vid_ch4)
     $            +rxt(k,rid_jch3cl)*y(k,vid_ch3cl)
     $            +rxt(k,rid_jch3br)*y(k,vid_ch3br)
     $            +rxt(k,rid_c17)*y(k,vid_ch3ooh)*y(k,vid_oh)
            loss(k,27) = ((rxt(k,rid_c17) +rxt(k,rid_c44))
     $           *y(k,vid_oh) + rxt(k,rid_jch3ooh) + het_rates(k,3))
     $           *y(k,vid_ch3ooh)
            prod(k,27) =rxt(k,rid_c7)*y(k,vid_ch3o2)*y(k,vid_ho2)
            loss(k,42) = (rxt(k,rid_hk2)*y(k,vid_o3p)
     $            +rxt(k,rid_hk5b)*y(k,vid_o1d) +rxt(k,rid_a1)
     $           *y(k,vid_h) +rxt(k,rid_b7)*y(k,vid_n)
     $            +rxt(k,rid_hk8)*y(k,vid_o2dg) + rxt(k,rid_jo2_op)
     $            + rxt(k,rid_jo2_od) + rxt(k,rid_j_o2s))
     $           *y(k,vid_o2)
            prod(k,42) = (2.000*rxt(k,rid_a6b)*y(k,vid_o3) +
     $           rxt(k,rid_a7)*y(k,vid_o3p) +
     $           rxt(k,rid_a17)*y(k,vid_oh) +
     $           rxt(k,rid_a23b)*y(k,vid_h) +
     $           rxt(k,rid_a27)*y(k,vid_ho2) +
     $           rxt(k,rid_b73a)*y(k,vid_no3) +
     $           rxt(k,rid_b73b)*y(k,vid_no3) +
     $           rxt(k,rid_c7)*y(k,vid_ch3o2) +
     $           rxt(k,rid_d7)*y(k,vid_cl) +
     $           rxt(k,rid_d33)*y(k,vid_clo) +
     $           rxt(k,rid_e7)*y(k,vid_br) +
     $           rxt(k,rid_e15)*y(k,vid_bro))*y(k,vid_ho2)
     $            + (rxt(k,rid_jo3_op) +rxt(k,rid_a2)*y(k,vid_h) +
     $           rxt(k,rid_a6)*y(k,vid_oh) +
     $           rxt(k,rid_b4)*y(k,vid_no) +
     $           rxt(k,rid_b9)*y(k,vid_no2) +
     $           rxt(k,rid_d2)*y(k,vid_cl) +
     $           rxt(k,rid_e2)*y(k,vid_br) +
     $           2.000*rxt(k,rid_hk3)*y(k,vid_o3p) +
     $           2.000*rxt(k,rid_hk7a)*y(k,vid_o1d) +
     $           rxt(k,rid_hk7b)*y(k,vid_o1d))*y(k,vid_o3)
     $            + (rxt(k,rid_a5)*y(k,vid_oh) +
     $           rxt(k,rid_b3)*y(k,vid_no2) +
     $           rxt(k,rid_b71)*y(k,vid_no3) +
     $           rxt(k,rid_d3)*y(k,vid_clo) +
     $           rxt(k,rid_d64)*y(k,vid_oclo) +
     $           rxt(k,rid_e3)*y(k,vid_bro) +
     $           rxt(k,rid_hk1)*y(k,vid_o3p) +
     $           rxt(k,rid_hk10)*y(k,vid_o2dg))*y(k,vid_o3p)
     $            + (rxt(k,rid_d8a)*y(k,vid_oh) +
     $           rxt(k,rid_d48)*y(k,vid_clo) +
     $           rxt(k,rid_d49)*y(k,vid_clo) +
     $           rxt(k,rid_d74)*y(k,vid_no3) +
     $           rxt(k,rid_e5b)*y(k,vid_bro) +
     $           rxt(k,rid_e5c)*y(k,vid_bro))*y(k,vid_clo)
     $            + (rxt(k,rid_hk9) +rxt(k,rid_hk30) +
     $           2.000*rxt(k,rid_hk8)*y(k,vid_o2))*y(k,vid_o2dg)
     $            + (rxt(k,rid_b28)*y(k,vid_ho2no2) +
     $           rxt(k,rid_d62)*y(k,vid_oclo))*y(k,vid_oh)
     $            + (rxt(k,rid_jcl2o2) +rxt(k,rid_d72)*y(k,vid_cl))
     $           *y(k,vid_cl2o2) +rxt(k,rid_b38)*y(k,vid_o1d)
     $           *y(k,vid_n2o) +rxt(k,rid_jno3_no)*y(k,vid_no3)
     $            +rxt(k,rid_e6)*y(k,vid_bro)*y(k,vid_bro)
     $            +rxt(k,rid_hk31)*y(k,vid_o2s)
            loss(k,16) = (rxt(k,rid_hk10)*y(k,vid_o3p)
     $            +rxt(k,rid_hk8)*y(k,vid_o2) + rxt(k,rid_hk9)
     $            + rxt(k,rid_hk30))*y(k,vid_o2dg)
            prod(k,16) = (rxt(k,rid_hk12) +
     $           rxt(k,rid_hk13)*y(k,vid_co2) +
     $           rxt(k,rid_hk14)*y(k,vid_o3) +
     $           rxt(k,rid_hk15)*y(k,vid_o3p) +
     $           rxt(k,rid_hk16)*y(k,vid_o2))*y(k,vid_o2s)
     $            +rxt(k,rid_jo3_od)*y(k,vid_o3)
            loss(k,17) = (rxt(k,rid_hk13)*y(k,vid_co2)
     $            +rxt(k,rid_hk14)*y(k,vid_o3) +rxt(k,rid_hk15)
     $           *y(k,vid_o3p) +rxt(k,rid_hk16)*y(k,vid_o2)
     $            + rxt(k,rid_hk12) + rxt(k,rid_hk31))*y(k,vid_o2s)
            prod(k,17) = (rxt(k,rid_j_o2s) +
     $           rxt(k,rid_hk5b)*y(k,vid_o1d))*y(k,vid_o2)
            loss(k,2) = 0.
            prod(k,2) = 0.
         end if
      end do

      end subroutine IMP_PROD_LOSS
