! subversion Id for THIS file : $Id: socpp-linmat.f 8506 2016-01-28 10:09:58Z simonc $
! $URL: http://svn-ae/ae/COMMON/stand-alone/atmos_models/socrates/tags/07.18.01/src/socpp-linmat.f $
!-----------------------------------------------------------------------
! DO NOT EDIT THIS FILE!! It was automatically written by
! the socpp program. Use that program and its *.in input file
! (see directory preproc/ ) to overwrite it
!============================================================

      subroutine LINMAT( mat
     $,                  y
     $,                  rxt
     $,                  het_rates
     $,                  kl, ku )

      use RXT_NAMES
      use SPC_NAMES


      implicit none

!----------------------------------------------
!       ... Dummy arguments
!----------------------------------------------
      integer, intent(in) ::   kl, ku
      real, intent(in) ::   y(4,56)
      real, intent(in) ::   rxt(4,202)
      real, intent(in) ::   het_rates(4,7)
      real, intent(out) ::  mat(4,573)


!----------------------------------------------
!       ... Local variables
!----------------------------------------------
      integer :: k

!----------------------------------------------
!       ... Linear Matrix entries for Implicit species
!----------------------------------------------

      do k = kl,ku
         mat(k,39) = -( rxt(k,rid_jn2o) )
         mat(k,352) = rxt(k,rid_hk21)

         mat(k,147) = -( rxt(k,rid_jch4) )

         mat(k,173) = -( rxt(k,rid_jh2o) )

         mat(k,84) = rxt(k,rid_jco2)
         mat(k,226) = rxt(k,rid_jch2o_h) + rxt(k,rid_jch2o_h2)

         mat(k,216) = -( rxt(k,rid_jhcl) + het_rates(k,4) )

         mat(k,141) = -( het_rates(k,7) )

         mat(k,83) = -( rxt(k,rid_jco2) )

         mat(k,229) = rxt(k,rid_jch2o_h2)

         mat(k,231) = -( rxt(k,rid_jch2o_h) + rxt(k,rid_jch2o_h2)
     $           + het_rates(k,6) )
         mat(k,112) = rxt(k,rid_jch3ooh)

         mat(k,3) = -( rxt(k,rid_jcfc10) )

         mat(k,7) = -( rxt(k,rid_jcfc11) )

         mat(k,11) = -( rxt(k,rid_jcfc12) )

         mat(k,15) = -( rxt(k,rid_jcfc113) )

         mat(k,19) = -( rxt(k,rid_jcfc114) )

         mat(k,23) = -( rxt(k,rid_jcfc115) )

         mat(k,76) = -( rxt(k,rid_jhcfc22) )

         mat(k,30) = -( rxt(k,rid_jch3ccl3) )

         mat(k,94) = -( rxt(k,rid_jch3cl) )

         mat(k,35) = -( rxt(k,rid_jha1211) )

         mat(k,27) = -( rxt(k,rid_jha1301) )

         mat(k,14) = 3.000*rxt(k,rid_jcfc113)
         mat(k,75) = 2.000*rxt(k,rid_jhcfc22)
         mat(k,34) = 2.000*rxt(k,rid_jha1211)
         mat(k,26) = 3.000*rxt(k,rid_jha1301)
         mat(k,18) = 4.000*rxt(k,rid_jcfc114)
         mat(k,22) = 5.000*rxt(k,rid_jcfc115)

         mat(k,87) = -( rxt(k,rid_jch3br) )

         mat(k,43) = -( rxt(k,rid_jchbr3) )

         mat(k,527) = -( rxt(k,rid_jo3_op) + rxt(k,rid_jo3_od) )

         mat(k,250) = 2.000*rxt(k,rid_jo2_op) + rxt(k,rid_jo2_od)
         mat(k,524) = rxt(k,rid_jo3_op)
         mat(k,547) = rxt(k,rid_jno2)
         mat(k,264) = rxt(k,rid_joclo)
         mat(k,508) = rxt(k,rid_jno3_no2)
         mat(k,418) = rxt(k,rid_jno)
         mat(k,282) = rxt(k,rid_jbro)
         mat(k,399) = rxt(k,rid_jho2)
         mat(k,372) = rxt(k,rid_hk4)

         mat(k,368) = -( rxt(k,rid_hk4) + rxt(k,rid_hk21) )
         mat(k,247) = rxt(k,rid_jo2_od)
         mat(k,41) = rxt(k,rid_jn2o)
         mat(k,86) = rxt(k,rid_jco2)
         mat(k,520) = rxt(k,rid_jo3_od)

         mat(k,176) = rxt(k,rid_jh2o)
         mat(k,157) = rxt(k,rid_jch4)
         mat(k,239) = rxt(k,rid_jch2o_h)
         mat(k,221) = rxt(k,rid_jhcl)

         mat(k,174) = rxt(k,rid_jh2o)
         mat(k,131) = rxt(k,rid_jhno3)
         mat(k,203) = rxt(k,rid_jhocl)
         mat(k,118) = rxt(k,rid_jhno4_2)
         mat(k,125) = 2.000*rxt(k,rid_jh2o2)
         mat(k,49) = rxt(k,rid_jhobr)
         mat(k,113) = rxt(k,rid_jch3ooh)
         mat(k,394) = rxt(k,rid_jho2)

         mat(k,396) = -( rxt(k,rid_jho2) )
         mat(k,119) = rxt(k,rid_jhno4_1) + rxt(k,rid_b24)
         mat(k,236) = rxt(k,rid_jch2o_h)
         mat(k,114) = rxt(k,rid_jch3ooh)

         mat(k,122) = -( rxt(k,rid_jh2o2) + het_rates(k,2) )

         mat(k,13) = 2.000*rxt(k,rid_jcfc12)
         mat(k,9) = 3.000*rxt(k,rid_jcfc11)
         mat(k,5) = 4.000*rxt(k,rid_jcfc10)
         mat(k,205) = rxt(k,rid_jhocl)
         mat(k,33) = 3.000*rxt(k,rid_jch3ccl3)
         mat(k,101) = rxt(k,rid_jch3cl)
         mat(k,17) = 3.000*rxt(k,rid_jcfc113)
         mat(k,80) = rxt(k,rid_jhcfc22)
         mat(k,38) = rxt(k,rid_jha1211)
         mat(k,68) = 2.000*rxt(k,rid_jcl2o2)
         mat(k,162) = 2.000*rxt(k,rid_jcl2)
         mat(k,21) = 2.000*rxt(k,rid_jcfc114)
         mat(k,25) = rxt(k,rid_jcfc115)
         mat(k,219) = rxt(k,rid_jhcl)
         mat(k,63) = rxt(k,rid_jclno2)
         mat(k,52) = rxt(k,rid_jbrcl)
         mat(k,193) = rxt(k,rid_jclno4_2)

         mat(k,158) = -( rxt(k,rid_jcl2) )

         mat(k,198) = rxt(k,rid_jclno4_1)
         mat(k,269) = rxt(k,rid_joclo)
         mat(k,69) = 2.000*rxt(k,rid_d61)

         mat(k,256) = -( rxt(k,rid_joclo) )

         mat(k,201) = -( rxt(k,rid_jhocl) )
         mat(k,189) = rxt(k,rid_g1) + rxt(k,rid_het1)
     $                + rxt(k,rid_PMChet1)

         mat(k,188) = -( rxt(k,rid_jclno4_1) + rxt(k,rid_jclno4_2)
     $                + rxt(k,rid_g1) + rxt(k,rid_het1)
     $                + rxt(k,rid_PMChet1) )

         mat(k,62) = -( rxt(k,rid_jclno2) )

         mat(k,65) = -( rxt(k,rid_jcl2o2) + rxt(k,rid_d61) )

         mat(k,405) = rxt(k,rid_jno)

         mat(k,416) = -( rxt(k,rid_jno) )
         mat(k,545) = rxt(k,rid_jno2)
         mat(k,506) = rxt(k,rid_jno3_no)

         mat(k,551) = -( rxt(k,rid_jno2) )
         mat(k,133) = rxt(k,rid_jhno3)
         mat(k,121) = rxt(k,rid_jhno4_1) + rxt(k,rid_b24)
         mat(k,197) = rxt(k,rid_jclno4_1)
         mat(k,108) = rxt(k,rid_jn2o5) + rxt(k,rid_b32)
         mat(k,74) = .710*rxt(k,rid_jbrono2)
         mat(k,64) = rxt(k,rid_jclno2)
         mat(k,512) = rxt(k,rid_jno3_no2)

         mat(k,510) = -( rxt(k,rid_jno3_no2) + rxt(k,rid_jno3_no) )
         mat(k,120) = rxt(k,rid_jhno4_2)
         mat(k,107) = rxt(k,rid_jn2o5) + rxt(k,rid_b32)
         mat(k,73) = .290*rxt(k,rid_jbrono2)
         mat(k,196) = rxt(k,rid_jclno4_2)

         mat(k,129) = -( rxt(k,rid_jhno3) + het_rates(k,1) )
         mat(k,185) = rxt(k,rid_g1) + rxt(k,rid_het1)
     $                + rxt(k,rid_PMChet1)
         mat(k,104) = 2.000*rxt(k,rid_g2) + 2.000*rxt(k,rid_het3)
     $                + 2.000*rxt(k,rid_PMChet3)

         mat(k,103) = -( rxt(k,rid_jn2o5) + rxt(k,rid_b32)
     $                + rxt(k,rid_g2) + rxt(k,rid_het3)
     $                + rxt(k,rid_PMChet3) )

         mat(k,115) = -( rxt(k,rid_jhno4_1) + rxt(k,rid_jhno4_2)
     $                + rxt(k,rid_b24) + het_rates(k,5) )

         mat(k,36) = rxt(k,rid_jha1211)
         mat(k,28) = rxt(k,rid_jha1301)
         mat(k,72) = .290*rxt(k,rid_jbrono2)
         mat(k,48) = rxt(k,rid_jhobr)
         mat(k,90) = rxt(k,rid_jch3br)
         mat(k,51) = rxt(k,rid_jbrcl)
         mat(k,276) = rxt(k,rid_jbro)
         mat(k,45) = 3.000*rxt(k,rid_jchbr3)

         mat(k,275) = -( rxt(k,rid_jbro) )
         mat(k,71) = .710*rxt(k,rid_jbrono2)

         mat(k,47) = -( rxt(k,rid_jhobr) )

         mat(k,70) = -( rxt(k,rid_jbrono2) )

         mat(k,50) = -( rxt(k,rid_jbrcl) )

         mat(k,148) = rxt(k,rid_jch4)
         mat(k,96) = rxt(k,rid_jch3cl)
         mat(k,88) = rxt(k,rid_jch3br)

         mat(k,109) = -( rxt(k,rid_jch3ooh) + het_rates(k,3) )

         mat(k,246) = -( rxt(k,rid_jo2_op) + rxt(k,rid_jo2_od)
     $                + rxt(k,rid_j_o2s) )
         mat(k,516) = rxt(k,rid_jo3_op)
         mat(k,67) = rxt(k,rid_jcl2o2)
         mat(k,501) = rxt(k,rid_jno3_no)
         mat(k,54) = rxt(k,rid_hk9) + rxt(k,rid_hk30)
         mat(k,57) = rxt(k,rid_hk31)

         mat(k,53) = -( rxt(k,rid_hk9) + rxt(k,rid_hk30) )
         mat(k,514) = rxt(k,rid_jo3_od)
         mat(k,55) = rxt(k,rid_hk12)

         mat(k,56) = -( rxt(k,rid_hk12) + rxt(k,rid_hk31) )
         mat(k,244) = rxt(k,rid_j_o2s)


      end do

      end subroutine LINMAT
