! subversion Id for THIS file : $Id: socpp-second.f 8506 2016-01-28 10:09:58Z simonc $
! $URL: http://svn-ae/ae/COMMON/stand-alone/atmos_models/socrates/tags/07.18.01/src/socpp-second.f $
!-----------------------------------------------------------------------
! DO NOT EDIT THIS FILE!! It was automatically written by
! the socpp program. Use that program and its *.in input file
! (see directory preproc/ ) to overwrite it
!============================================================

      real function SECOND()
!-------------------------------------------------------------
!	... Elapsed timer function
!-------------------------------------------------------------

      implicit none

      real(4) :: times(2), eltime
      real(4) :: ETIME

      eltime = ETIME( times )
      SECOND = DBLE( eltime )

      end function SECOND
